files:
    transcripts: Inputs/test_transcript_file.txt
    gencode: Inputs/gencode.v37.transcripts.fa
    readout: Inputs/Readout_probes_information.csv
    barcode: Inputs/barcodes_merfish.csv
    index: Inputs/Genome-Index

path:
    src: src/

primers:
    forward: GGGCCACGTCCTCAATCGAC
    reverse: CCCTCGCCAAGGTTCGCTAG


output:
    probes_for_alligning: Outputs/probes_for_alligning.fasta
    complement_initial_probes: Outputs/complement_initial_probes.fasta
    split_probes_for_alligning: Outputs/split_probes_for_alligning.fasta
    split_complement_initial_probes: Outputs/split_complement_initial_probes.fasta
    uniquely_mapped_probes: Outputs/mapped_reads/uniquely_mapped_probes-
    uniquely_mapped_probes_probenames:  Outputs/mapped_reads/uniquely_mapped_probes_probenames.txt
    uniquely_mapped_probes_selected_sam: Outputs/mapped_reads/uniquely_mapped_probes_selected.sam
    split_complement_sequence: Outputs/split_complement_sequence.fasta
    encoding_probes: Outputs/encoding_probes.fasta
    filtered_probes: Outputs/filtered_probes.fasta
    probe_stats: Results/probe_stats.csv
    uniquely_mapped_probes_selected_probes_fasta: Results/uniquely_mapped_probes_filtered_final.fasta
    complement_probes: Outputs/complement_probes.fasta
    blastdb: Outputs/blastdb/complement_probes_db
    blast_results: Results/blast_results.out
    Final_Probe_results: Results/Final_Probe_results.csv



parameters:
    kmer_length: 30
    kmer_overlap: 20
    GC_lower_bound: 43
    GC_upper_bound: 63
    Temp_lower_bound: 66
    Temp_upper_bound: 76
    probe_length: 135
