files:
    transcripts: Probedesign/test_transcript_file.txt
    gencode: Probedesign/gencode.v37.transcripts.fa
    readout: Probedesign/Readout_probes_information.csv
    barcode: Probedesign/barcodes_merfish.csv
    reference: "ALEJANDRO TELL ME WHEEEEEEEERE"
path:
    src: Probedesign/src/

primers:
    forward: GGGCCACGTCCTCAATCGAC
    reverse: CCCTCGCCAAGGTTCGCTAG

inputs:
    kmer_fasta:

output:
    encoding_probes: Probedesign/output/encoding_probes.fasta
    complement_sequence: Probedesign/output/complement_sequence.fasta
    split_complement_sequence: Probedesign/output/split_complement_sequence.fasta
    filtered_probes: Probedesign/output/filtered_probes.fasta
    probe_stats: Probedesign/output/probe_stats.csv
    mapped_reads: Probedesign/output/mapped_reads/filtered_probes.bam
    sorted_reads: Probedesign/output/sorted_reads/sorted_filtered_probes.bam
    sorted_reads_index: Probedesign/output/sorted_reads/sorted_filtered_probes.bai
    blastdb: Probedesign/output/blastdb/filtered_probes
    blast_results: Probedesign/output/blast_results.out

exec:
    faidx: /data/leuven/337/vsc33740/miniconda3/envs/snakemake/bin/faidx
    pyfasta: /data/leuven/337/vsc33740/miniconda3/envs/snakemake/bin/pyfasta
    python: /data/leuven/337/vsc33740/miniconda3/envs/snakemake/bin/python
    bwa: /data/leuven/337/vsc33740/miniconda3/envs/snakemake/bin/bwa

parameters:
    kmer_length: 30
    kmer_overlap: 20
    GC_lower_bound: 43
    GC_upper_bound: 63
    Temp_lower_bound: 66
    Temp_upper_bound: 76
    probe_length: 135
