files:
    transcripts: Inputs/transcript_file.txt
    gencode: Inputs/gencode.v37.transcripts.fa
    readout: Inputs/Readout_probes_information.csv
    barcode: Inputs/barcodes_merfish.csv
    index: Inputs/Genome-Index

path:
    src: src/

primers:
    forward: GGGCCACGTCCTCAATCGAC
    reverse: CCCTCGCCAAGGTTCGCTAG


output:
    probes_for_alligning: probes_for_alligning.fasta
    complement_initial_probes: complement_initial_probes.fasta
    split_probes_for_alligning: split_probes_for_alligning.fasta
    split_complement_initial_probes: split_complement_initial_probes.fasta
    uniquely_mapped_probes: uniquely_mapped_probes-
    uniquely_mapped_probes_probenames: uniquely_mapped_probes_probenames.txt
    uniquely_mapped_probes_selected_sam: uniquely_mapped_probes_selected.sam
    split_complement_sequence: split_complement_sequence.fasta
    encoding_probes: encoding_probes.fasta
    filtered_probes: filtered_probes.fasta
    probe_stats: probe_stats.csv
    uniquely_mapped_probes_filtered_final: uniquely_mapped_probes_filtered_final.fasta
    complement_probes: complement_probes.fasta
    blastdb: blastdb/complement_probes_db
    blast_results: blast_results.out
    Final_Probe_results: Final_Probe_results.csv



parameters:
    kmer_length: 30
    kmer_overlap: 20
    GC_lower_bound: 43
    GC_upper_bound: 63
    Temp_lower_bound: 66
    Temp_upper_bound: 76
    probe_length: 135
